update test readability

diff --git a/.github/workflows/reusable-testings.yaml b/.github/workflows/reusable-testings.yaml
--- a/.github/workflows/reusable-testings.yaml
+++ b/.github/workflows/reusable-testings.yaml
@@ -93,6 +93,9 @@ jobs:
     - name: Make Test
       run: make test
 
+    - name: check how it looks
+      run: exit 1
+
   validate-release:
     if: ${{ startsWith(github.head_ref, 'release/') }}
 
@@ -131,7 +134,7 @@ jobs:
       run: |
         # compare release branch and software build version
         if [ "${{ needs.build.outputs.BUILD_VERSION}}" != "${{steps.set-release-branch.outputs.GITHUB_SPEC_VER}}" ]; then
-          echo "Issues: Release Branch Specified Version is different from Build Version."
+          echo "Error: Release Branch Specified Version is different from Build Version."
           exit 1
         fi
 
@@ -140,6 +143,6 @@ jobs:
         # check duplicate tag
         TAG_EXIST="$(git ls-remote origin refs/tags/${{ needs.build.outputs.BUILD_VERSION }} | awk '{print $2}' | sed 's/refs\/tags\///g')"
         if [ -n "$TAG_EXIST" ]; then
-          echo "remote origin tag - $TAG_EXIST - exists already"
+          echo "Error: Tag ($TAG_EXIST) exists already at remote origin"
           exit 1
         fi
